version: "2"

services:
    uwsgi:
        image: addressbooks
        ports:
            - "80:8080"
        env_file: "secrets.env"
        depends_on: 
            - "postgres"
        restart: "always"
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=addressbooks
            - POSTGRES_PASSWORD=addressbooks
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - "./pgdata:/var/lib/postgresql/data/pgdata/"
        restart: "always"
    redis:
        image: redis
        restart: "always"
